# Generated by Django 2.2.12 on 2022-03-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20220301_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalhes'),
        ),
    ]
